Vagrant.configure(2) do |config|
	config.vm.box = "lucid32"

	config.vm.network "forwarded_port", guest: 80, host:8080 
 
	config.vm.network "forwarded_port", guest: 9999, host: 8090
   
	config.vm.synced_folder "~/Documents/Github/Senac-TCC/source/IDS", "/home/vagrant/go"

	config.vm.provision :shell, :path => "bootstrap.sh"
end
