Vagrant.configure(2) do |config|

  config.vm.network "forwarded_port", guest: 80, host:8080 
 
  config.vm.network "forwarded_port", guest: 9999, host: 8090
   
  config.vm.synced_folder "C:\\desenvolvimento\\ubuntu", "/home/vagrant/go"
  
end
