Vagrant.configure(2) do |config|
  config.vm.box = "lucid32"
  config.vm.network "forwarded_port", guest: 80, host:8080 
  config.vm.synced_folder "C:\\Users\\rmendonca\\Documents\\GitHub\\Senac-TCC\\source\\Projeto", "/home/vagrant/go"
  config.ssh.insert_key = false
end